language: php

dist: trusty
sudo: false

php:
 - 7.2
branches:
 - master
 
before_script:
 - git clone https://github.com/krakjoe/pthreads.git --depth=1
 - cd pthreads
 - phpize
 - ./configure
 - make
 - make install
 - cd /home/travis/build/
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - git clone --recursive https://github.com/pmmp/PocketMine-MP.git --depth=1
 - git clone https://github.com/pmmp/PocketMine-DevTools.git
 - mkdir -p PocketMine-MP/plugins/VGCore
 - cp -rf /home/travis/build/CaptainDuck/VGCore/src PocketMine-MP/plugins/VGCore/
 - cp -rf /home/travis/build/CaptainDuck/VGCore/plugin.yml PocketMine-MP/plugins/VGCore/
 - cp -rf /home/travis/build/CaptainDuck/VGCore/Travis.php PocketMine-MP/plugins/VGCore/
 - cp -rf /home/travis/build/CaptainDuck/VGCore/compile.php PocketMine-MP/plugins/VGCore/
 - cp -rf /home/travis/build/CaptainDuck/VGCore/LICENSE PocketMine-MP/plugins/VGCore/
 - cp CaptainDuck/VGCore/compile.php /home/travis/build/
 - cp CaptainDuck/VGCore/Travis.php /home/travis/build/PocketMine-MP/
 - php compile.php
 - cd PocketMine-MP
 - composer install
 
script:
 - ls -R
 - php Travis.php

deploy:
  provider: releases
  api_key: "61beb484801e3c6e9a89dedbf2ce056cebbbae84"
  file: "/home/travis/build/PocketMine-MP/plugins/DevTools/VGCore.phar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false

notifications:
 email: false
